name: 'Release Packages'

description: 'Build, Pack and Push'

inputs:
  tag:
    description: 'The Git tag that triggered this workflow'
    required: true
  nuget_api_key:
    description: 'The API key for NuGet package repository'
    required: true
  enable_push:
    description: 'Enable Nuget push'
    required: true
    default: 'no'

runs:
  using: 'composite'
  steps:

    - name: Extract package version
      run: echo "PACKAGE_VERSION=${{ inputs.ref_name }}" >> $GITHUB_ENV
      shell: bash

    - name: Extract assembly version
      run: echo "ASSEMBLY_VERSION=$(echo \"${{ inputs.ref_name }}\" | grep -o '^[0-9]*\.[0-9]*\.[0-9]*').0" >> $GITHUB_ENV
      shell: bash

    - name: Build projects
      run: |
        for sln in $(find . -name '*.sln'); do
          echo -e "\n\033[0;34mBuilding $sln \033[0m"
          dotnet build "$sln" -c Release /p:Version=${{ env.PACKAGE_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:FileVersion=${{ env.ASSEMBLY_VERSION }}
        done
      shell: bash

    - name: Pack
      run: find . -name '*.sln' | parallel --jobs 0 'dotnet pack {} /p:PackageVersion=${{env.PACKAGE_VERSION}} -c Release -o ./out --no-build --include-symbols --include-source --verbosity Minimal'
      shell: bash
    
    - name: Push
      if: ${{ inputs.enable_push == 'yes' }}
      run: |
        find . -name '*.nupkg' | grep -v '.sources.nupkg' | parallel --jobs 0 'dotnet nuget push {} --api-key ${{ inputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json'
      shell: bash